### ISSUE TITLE
Errors are swallowed and causes other plugins to fail

### ISSUE THREAD

**Issue by benedfit** [stackbithq/sourcebit-transform-assets#11]
When an error is encountered during downloading an asset, the error is swallowed, and subsequent plugins fail. 

I have into this issue when using in combination with the Next plugin. One of my external assets failed to download, and it caused the entire Next plugin to fail as the cache was not created behind the scenes

**Comment by smnh** [comment]
Hi @benedfit,

What's up? :)
Do you have an example project or steps to reproduce

**Comment by benedfit** [comment]
Hey @smnh, I'm good thanks, how are things at Stackbit?

It mostly happens locally, but let me create a repo to reproduce it. I am planning to offer up a fix for it too
